// <auto-generated />
using System;
using AggretationApp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AggretationApp.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221030144917_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AggregationAPI.Models.Data.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OBJ_GV_TIPAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OBJ_NUMERIS")
                        .HasColumnType("int");

                    b.Property<string>("OBT_PAVADINIMAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PL_T")
                        .HasColumnType("datetime2");

                    b.Property<double?>("P_MINUS")
                        .HasColumnType("float");

                    b.Property<double?>("P_PLUS")
                        .HasColumnType("float");

                    b.Property<string>("TINKLAS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
